apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-config
  namespace: bookstore
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "bookstore"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
