apiVersion: v1
kind: Secret
metadata:
  name: bookstore-secret
  namespace: bookstore
type: Opaque
stringData:
  DB_USER: "bookstore"
  DB_PASSWORD: "bookstore123"
  POSTGRES_PASSWORD: "bookstore123"
